services:
  blog-db:
    image: mysql
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: start-first
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-h'
        - localhost
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - blog-db-vol:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - blog-app-net
  blog-server:
    image: codersgyan/advance-ai-agent:build-484cc4c5d4c93b73f2fa1fd42514d3b55e33934b
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: start-first
    healthcheck:
      test:
        - CMD
        - wget
        - '--no-verbose'
        - '--tries=1'
        - '--spider'
        - http://localhost:3000/health
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - '3001:3000'
    environment:
      - DB_HOST=blog-db
      - DB_USER=root
      - DB_PASSWORD=/run/secrets/my_db_password
      - DB_NAME=blogdb
      - NODE_HOST="{{.Node.Hostname}}"
    networks:
      - blog-app-net
    secrets:
      - my_db_password
volumes:
  blog-db-vol: null
networks:
  blog-app-net: null
